CREATE TABLE IF NOT EXISTS USER(
	"UID" INTEGER PRIMARY KEY,
	"UNAME" TEXT,
	"USERNAME" TEXT,
	"EMAIL" TEXT,
	"ADDRESS" INTEGER,
	"PHONE" TEXT,
	"WEBSITE" TEXT,
	"COMPANY" INTEGER
);

CREATE TABLE IF NOT EXISTS ADDRESS(
	"ID" INTEGER PRIMARY KEY,
	"STREET" TEXT,
	"SUITE" TEXT,
	"CITY" TEXT,
	"ZIPCODE" TEXT,
	"GEO" INTEGER
);

CREATE TABLE IF NOT EXISTS GEO(
	"ID" INTEGER PRIMARY KEY,
	"LAT" TEXT,
	"LNG" TEXT
);

CREATE TABLE IF NOT EXISTS COMPANY(
	"ID" INTEGER PRIMARY KEY,
	"NAME" TEXT,
	"CATCHPHRASE" TEXT,
	"BS" TEXT
);